// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06.05.2025, 02:05:53
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/new/Desktop/Tandau/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/new/Desktop/Tandau/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/new/Desktop/Tandau/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/new/Desktop/Tandau/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/new/Desktop/Tandau/plugins/**/*.{js,ts,mjs}","/Users/new/Desktop/Tandau/composables/**/*.{js,ts,mjs}","/Users/new/Desktop/Tandau/utils/**/*.{js,ts,mjs}","/Users/new/Desktop/Tandau/pages/index.vue","/Users/new/Desktop/Tandau/pages/chat/index.vue","/Users/new/Desktop/Tandau/pages/study/index.vue","/Users/new/Desktop/Tandau/pages/auth/callback.vue","/Users/new/Desktop/Tandau/pages/profile/index.vue","/Users/new/Desktop/Tandau/pages/sign-in/index.vue","/Users/new/Desktop/Tandau/pages/sign-up/index.vue","/Users/new/Desktop/Tandau/pages/study/kz/index.vue","/Users/new/Desktop/Tandau/pages/favorites/index.vue","/Users/new/Desktop/Tandau/pages/study/abroad/index.vue","/Users/new/Desktop/Tandau/pages/study/kz/specialties.vue","/Users/new/Desktop/Tandau/pages/forgot-password/index.vue","/Users/new/Desktop/Tandau/pages/study/abroad/[id]/index.vue","/Users/new/Desktop/Tandau/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/new/Desktop/Tandau/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/new/Desktop/Tandau/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;